[package]
name = "diffsol"
version = "0.1.11"
edition = "2021"
description = "A library for solving ordinary differential equations (ODEs) in Rust."
license = "MIT"
authors = ["Martin Robinson <martinjrobins@gmail.com>"]
repository = "https://github.com/martinjrobins/diffsol"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["nalgebra", "faer"]
faer = []
nalgebra = []
sundials = ["suitesparse_sys"]
suitesparse = ["suitesparse_sys"]
diffsl = []
diffsl-llvm4 = ["diffsl4-0", "diffsl"]
diffsl-llvm5 = ["diffsl5-0", "diffsl"]
diffsl-llvm6 = ["diffsl6-0", "diffsl"]
diffsl-llvm7 = ["diffsl7-0", "diffsl"]
diffsl-llvm8 = ["diffsl8-0", "diffsl"]
diffsl-llvm9 = ["diffsl9-0", "diffsl"]
diffsl-llvm10 = ["diffsl10-0", "diffsl"]
diffsl-llvm11 = ["diffsl11-0", "diffsl"]
diffsl-llvm12 = ["diffsl12-0", "diffsl"]
diffsl-llvm13 = ["diffsl13-0", "diffsl"]
diffsl-llvm14 = ["diffsl14-0", "diffsl"]
diffsl-llvm15 = ["diffsl15-0", "diffsl"]
diffsl-llvm16 = ["diffsl16-0", "diffsl"]
diffsl-llvm17 = ["diffsl17-0", "diffsl"]

[dependencies]
nalgebra = "0.33"
nalgebra-sparse = { version = "0.10", features = ["io"] }
anyhow = "1.0.86"
num-traits = "0.2.17"
ouroboros = "0.18.2"
serde = { version = "1.0.196", features = ["derive"] }
diffsl4-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm4-0"], optional = true }
diffsl5-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm5-0"], optional = true }
diffsl6-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm6-0"], optional = true }
diffsl7-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm7-0"], optional = true }
diffsl8-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm8-0"], optional = true }
diffsl9-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm9-0"], optional = true }
diffsl10-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm10-0"], optional = true }
diffsl11-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm11-0"], optional = true }
diffsl12-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm12-0"], optional = true }
diffsl13-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm13-0"], optional = true }
diffsl14-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm14-0"], optional = true }
diffsl15-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm15-0"], optional = true }
diffsl16-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm16-0"], optional = true }
diffsl17-0 = { package = "diffsl", version = ">=0.1.6", features = ["llvm17-0"], optional = true }
petgraph = "0.6.4"
faer = "0.18.2"
suitesparse_sys = { version = "0.1.3", optional = true }

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }
criterion = { version = "0.4" }

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.99"

[[bench]]
name = "ode_solvers"
harness = false

[package.metadata.docs.rs]
features = ["diffsl-llvm12"]

[profile.profiling]
inherits = "release"
debug = true
