[package]
name = "diffsol"
version = "0.2.1"
edition = "2021"
description = "A library for solving ordinary differential equations (ODEs) in Rust."
license = "MIT"
authors = ["Martin Robinson <martinjrobins@gmail.com>"]
repository = "https://github.com/martinjrobins/diffsol"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["nalgebra", "faer"]
faer = []
nalgebra = []
sundials = ["suitesparse_sys", "bindgen", "cc"]
suitesparse = ["suitesparse_sys"]
diffsl-cranelift = ["diffsl-no-llvm", "diffsl"]
diffsl = []
diffsl-llvm = []
diffsl-llvm13 = ["diffsl13-0", "diffsl-llvm", "diffsl"]
diffsl-llvm14 = ["diffsl14-0", "diffsl-llvm", "diffsl"]
diffsl-llvm15 = ["diffsl15-0", "diffsl-llvm", "diffsl"]
diffsl-llvm16 = ["diffsl16-0", "diffsl-llvm", "diffsl"]
diffsl-llvm17 = ["diffsl17-0", "diffsl-llvm", "diffsl"]

[dependencies]
nalgebra = "0.33"
nalgebra-sparse = { version = "0.10", features = ["io"] }
num-traits = "0.2.17"
ouroboros = "0.18.2"
serde = { version = "1.0.196", features = ["derive"] }
diffsl-no-llvm = { package = "diffsl", version = "=0.2.0", optional = true }
diffsl13-0 = { package = "diffsl", version = "=0.2.0", features = ["llvm13-0"], optional = true }
diffsl14-0 = { package = "diffsl", version = "=0.2.0", features = ["llvm14-0"], optional = true }
diffsl15-0 = { package = "diffsl", version = "=0.2.0", features = ["llvm15-0"], optional = true }
diffsl16-0 = { package = "diffsl", version = "=0.2.0", features = ["llvm16-0"], optional = true }
diffsl17-0 = { package = "diffsl", version = "=0.2.0", features = ["llvm17-0"], optional = true }
petgraph = "0.6.4"
faer = "0.19.4"
suitesparse_sys = { version = "0.1.3", optional = true }
thiserror = "1.0.63"

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }
criterion = { version = "0.5.1" }

[build-dependencies]
bindgen = { version = "0.70.1", optional = true }
cc = { version = "1.0.99", optional = true }

[[bench]]
name = "ode_solvers"
harness = false

[package.metadata.docs.rs]
features = ["diffsl-llvm15"]

[profile.profiling]
inherits = "release"
debug = true
