name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: ${{ github.workspace }}/.cargo
  RUSTFLAGS: -D warnings -A unused-imports
  RUSTDOCFLAGS: -D warnings
  RUST_BACKTRACE: full

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable --no-self-update
      - run: rustc -Vv
      - run: cargo fmt --all -- --check

  unit-tests:
    name: Tests - ${{ matrix.os }} - ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
          toolchain:
            - stable
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest
          include:
            - toolchain: beta
              os: ubuntu-latest
            - toolchain: nightly
              os: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3.3.2
      with:
        path: |
          ${{ env.CARGO_HOME }}
          target
        key: unit-test-${{ runner.os }}-${{ matrix.toolchain}}
    - name: Set up Rust
      run: rustup default ${{ matrix.toolchain }} && rustup update ${{ matrix.toolchain }} --no-self-update && rustup component add clippy
    - name: Rust version
      run: rustc -Vv
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
    - name: Set features variable and install dependencies
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          echo "ADDITIONAL_FEATURES_FLAGS=--features sundials" >> $GITHUB_ENV
          apt-get install -y libsuitesparse-dev
        else
          echo "ADDITIONAL_FEATURES_FLAGS=" >> $GITHUB_ENV
        fi
    - name: Run tests - default features
      run: cargo test --verbose 
    - name: Run tests - all features
      run: cargo test --verbose --features diffsl-llvm14 ${{ env.ADDITIONAL_FEATURES_FLAGS }}
    - name: Clippy - all features
      run: cargo clippy --verbose --features diffsl-llvm14 ${{ env.ADDITIONAL_FEATURES_FLAGS }}
    - name: Docs - all features
      run: cargo rustdoc --features diffsl-llvm14 --features sundials
